// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsLSsEGfDRSa16cKPoAzB6fZVKOopBUoY',
    appId: '1:492876542608:web:1c8d037c498e02709d9e15',
    messagingSenderId: '492876542608',
    projectId: 'workwithfirebase-b0656',
    authDomain: 'workwithfirebase-b0656.firebaseapp.com',
    storageBucket: 'workwithfirebase-b0656.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZaU4FoZvkdJB5_hArrH1u1PLxey1g3CU',
    appId: '1:492876542608:android:3e587e6e39599b539d9e15',
    messagingSenderId: '492876542608',
    projectId: 'workwithfirebase-b0656',
    storageBucket: 'workwithfirebase-b0656.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxg-FeyArvrbd8TXRVL9xHX2SK6t5p1zs',
    appId: '1:492876542608:ios:53188ab0412b5a629d9e15',
    messagingSenderId: '492876542608',
    projectId: 'workwithfirebase-b0656',
    storageBucket: 'workwithfirebase-b0656.appspot.com',
    iosClientId: '492876542608-c5d2q0jqr4voijtnh1rsd4mbthq207g9.apps.googleusercontent.com',
    iosBundleId: 'com.example.authWithKoko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxg-FeyArvrbd8TXRVL9xHX2SK6t5p1zs',
    appId: '1:492876542608:ios:53188ab0412b5a629d9e15',
    messagingSenderId: '492876542608',
    projectId: 'workwithfirebase-b0656',
    storageBucket: 'workwithfirebase-b0656.appspot.com',
    iosClientId: '492876542608-c5d2q0jqr4voijtnh1rsd4mbthq207g9.apps.googleusercontent.com',
    iosBundleId: 'com.example.authWithKoko',
  );
}
